title: Projectory
remote_theme: just-the-docs/just-the-docs
mermaid:
  version: "10.9.0" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title:  Tip
    color: purple
  info:
    title:  Info
    color: blue
  attention:
    title:  Attention
    color: yellow
  download:
    title:  Download
    color: grey-dk